import os

base = r'c:\Users\User\AndroidStudioProjects\ArrowFlow\app\src\main\res\layout'

# fragment_menu.xml
with open(os.path.join(base, 'fragment_menu.xml'), 'w', encoding='utf-8') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n')
    f.write('<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"\n')
    f.write('    xmlns:app="http://schemas.android.com/apk/res-auto"\n')
    f.write('    android:layout_width="match_parent"\n')
    f.write('    android:layout_height="match_parent"\n')
    f.write('    android:background="@color/bg_game">\n\n')
    f.write('    <ImageView android:id="@+id/ivLogo" android:layout_width="@dimen/logo_size" android:layout_height="@dimen/logo_size"\n')
    f.write('        android:src="@drawable/app_logo" android:contentDescription="@string/app_name"\n')
    f.write('        app:layout_constraintBottom_toTopOf="@+id/title" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"\n')
    f.write('        app:layout_constraintVertical_chainStyle="packed" />\n\n')
    f.write('    <TextView android:id="@+id/title" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_16" android:text="@string/app_name"\n')
    f.write('        app:layout_constraintBottom_toTopOf="@+id/tvStats" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/ivLogo"\n')
    f.write('        style="@style/TextAppearance.ArrowFlow.Title" />\n\n')
    f.write('    <TextView android:id="@+id/tvStats" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_8" android:background="@drawable/bg_hud_badge"\n')
    f.write('        android:paddingStart="@dimen/badge_padding_horizontal" android:paddingEnd="@dimen/badge_padding_horizontal"\n')
    f.write('        android:paddingTop="@dimen/badge_padding_vertical" android:paddingBottom="@dimen/badge_padding_vertical"\n')
    f.write('        android:textSize="@dimen/caption_text_size" android:textStyle="bold" android:textColor="@color/text_secondary"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@+id/title" />\n\n')
    f.write('    <com.google.android.material.button.MaterialButton android:id="@+id/btnStart"\n')
    f.write('        android:layout_width="240dp" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_32" android:text="@string/start_game"\n')
    f.write('        app:layout_constraintBottom_toTopOf="@+id/btnLevelSelect" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/tvStats"\n')
    f.write('        style="@style/Widget.ArrowFlow.Button.Primary" />\n\n')
    f.write('    <com.google.android.material.button.MaterialButton android:id="@+id/btnLevelSelect"\n')
    f.write('        android:layout_width="240dp" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_16" android:text="@string/level_select"\n')
    f.write('        app:layout_constraintBottom_toTopOf="@+id/btnSettings" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/btnStart"\n')
    f.write('        style="@style/Widget.ArrowFlow.Button.Secondary" />\n\n')
    f.write('    <com.google.android.material.button.MaterialButton android:id="@+id/btnSettings"\n')
    f.write('        android:layout_width="240dp" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_16" android:text="@string/settings"\n')
    f.write('        app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/btnLevelSelect"\n')
    f.write('        style="@style/Widget.ArrowFlow.Button.Secondary" />\n')
    f.write('</androidx.constraintlayout.widget.ConstraintLayout>\n')
print('fragment_menu.xml done')