import os

base = r'c:\Users\User\AndroidStudioProjects\ArrowFlow\app\src\main\res\layout'

# fragment_level_select.xml
with open(os.path.join(base, 'fragment_level_select.xml'), 'w', encoding='utf-8') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n')
    f.write('<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"\n')
    f.write('    xmlns:app="http://schemas.android.com/apk/res-auto"\n')
    f.write('    xmlns:tools="http://schemas.android.com/tools"\n')
    f.write('    android:layout_width="match_parent"\n')
    f.write('    android:layout_height="match_parent"\n')
    f.write('    android:background="@color/bg_game"\n')
    f.write('    android:padding="@dimen/spacing_16">\n\n')
    f.write('    <TextView android:id="@+id/tvTitle" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('        android:text="@string/select_level"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"\n')
    f.write('        style="@style/TextAppearance.ArrowFlow.Title" />\n\n')
    f.write('    <LinearLayout android:id="@+id/headerStats" android:layout_width="0dp" android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_8" android:orientation="vertical"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@+id/tvTitle">\n\n')
    f.write('        <TextView android:id="@+id/tvProgress" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('            style="@style/TextAppearance.ArrowFlow.Secondary" />\n\n')
    f.write('        <com.google.android.material.progressindicator.LinearProgressIndicator\n')
    f.write('            android:id="@+id/progressLevels" android:layout_width="match_parent" android:layout_height="wrap_content"\n')
    f.write('            android:layout_marginTop="@dimen/spacing_6" />\n')
    f.write('    </LinearLayout>\n\n')
    f.write('    <androidx.recyclerview.widget.RecyclerView android:id="@+id/rvLevels"\n')
    f.write('        android:layout_width="0dp" android:layout_height="0dp"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_16" android:clipToPadding="false"\n')
    f.write('        android:paddingBottom="@dimen/spacing_16"\n')
    f.write('        app:layoutManager="androidx.recyclerview.widget.GridLayoutManager" app:spanCount="3"\n')
    f.write('        app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/headerStats"\n')
    f.write('        tools:listitem="@layout/item_level" />\n')
    f.write('</androidx.constraintlayout.widget.ConstraintLayout>\n')
print('fragment_level_select.xml done')

# item_level.xml
with open(os.path.join(base, 'item_level.xml'), 'w', encoding='utf-8') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n')
    f.write('<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"\n')
    f.write('    xmlns:app="http://schemas.android.com/apk/res-auto"\n')
    f.write('    xmlns:tools="http://schemas.android.com/tools"\n')
    f.write('    android:layout_width="match_parent"\n')
    f.write('    android:layout_height="wrap_content"\n')
    f.write('    android:layout_margin="@dimen/spacing_6"\n')
    f.write('    style="@style/Widget.ArrowFlow.Card">\n\n')
    f.write('    <androidx.constraintlayout.widget.ConstraintLayout\n')
    f.write('        android:layout_width="match_parent"\n')
    f.write('        android:layout_height="wrap_content"\n')
    f.write('        android:padding="@dimen/spacing_12">\n\n')
    f.write('        <TextView android:id="@+id/tvLevelNumber" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('            app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"\n')
    f.write('            tools:text="LEVEL 1" style="@style/TextAppearance.ArrowFlow.SectionTitle" />\n\n')
    f.write('        <TextView android:id="@+id/tvDifficulty" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('            app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/tvLevelNumber"\n')
    f.write('            tools:text="EASY" style="@style/TextAppearance.ArrowFlow.Secondary" />\n\n')
    f.write('        <TextView android:id="@+id/tvStars" android:layout_width="wrap_content" android:layout_height="wrap_content"\n')
    f.write('            android:layout_marginTop="@dimen/spacing_4" android:textColor="@color/star_filled" android:textSize="18sp"\n')
    f.write('            app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toStartOf="parent"\n')
    f.write('            app:layout_constraintTop_toBottomOf="@+id/tvDifficulty" tools:text="⭐⭐⭐" />\n\n')
    f.write('        <ImageView android:id="@+id/ivLock" android:layout_width="@dimen/icon_size_medium" android:layout_height="@dimen/icon_size_medium"\n')
    f.write('            android:src="@android:drawable/ic_secure" android:visibility="gone"\n')
    f.write('            android:contentDescription="@string/locked"\n')
    f.write('            app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('            app:layout_constraintTop_toTopOf="parent" app:tint="@color/text_tertiary" />\n')
    f.write('    </androidx.constraintlayout.widget.ConstraintLayout>\n')
    f.write('</com.google.android.material.card.MaterialCardView>\n')
print('item_level.xml done')