import os

base = r'c:\Users\User\AndroidStudioProjects\ArrowFlow\app\src\main\res\layout'

# fragment_game.xml - part 1
with open(os.path.join(base, 'fragment_game.xml'), 'w', encoding='utf-8') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n')
    f.write('<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"\n')
    f.write('    xmlns:app="http://schemas.android.com/apk/res-auto"\n')
    f.write('    xmlns:tools="http://schemas.android.com/tools"\n')
    f.write('    android:layout_width="match_parent"\n')
    f.write('    android:layout_height="match_parent"\n')
    f.write('    android:background="@color/bg_game">\n\n')
    
    # Top Toolbar
    f.write('    <ImageButton\n')
    f.write('        android:id="@+id/btnBack"\n')
    f.write('        android:layout_width="48dp"\n')
    f.write('        android:layout_height="48dp"\n')
    f.write('        android:layout_marginStart="@dimen/spacing_12"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_8"\n')
    f.write('        android:background="?attr/selectableItemBackgroundBorderless"\n')
    f.write('        android:contentDescription="@string/back"\n')
    f.write('        android:src="@drawable/ic_back"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toTopOf="parent" />\n\n')
    
    f.write('    <TextView\n')
    f.write('        android:id="@+id/tvLevel"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="wrap_content"\n')
    f.write('        android:textColor="@color/text_primary"\n')
    f.write('        android:textSize="@dimen/subtitle_text_size"\n')
    f.write('        android:textStyle="bold"\n')
    f.write('        app:layout_constraintBottom_toBottomOf="@id/btnBack"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toTopOf="@id/btnBack"\n')
    f.write('        tools:text="Level 3" />\n\n')
    
    f.write('    <ImageButton\n')
    f.write('        android:id="@+id/btnSettings"\n')
    f.write('        android:layout_width="48dp"\n')
    f.write('        android:layout_height="48dp"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_8"\n')
    f.write('        android:layout_marginEnd="@dimen/spacing_12"\n')
    f.write('        android:background="?attr/selectableItemBackgroundBorderless"\n')
    f.write('        android:contentDescription="@string/settings"\n')
    f.write('        android:src="@drawable/ic_settings_gear"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintTop_toTopOf="parent" />\n\n')
    # HUD Row
    f.write('    <LinearLayout\n')
    f.write('        android:id="@+id/badgeArrowCount"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="@dimen/hud_height"\n')
    f.write('        android:layout_marginStart="@dimen/spacing_16"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_24"\n')
    f.write('        android:background="@drawable/bg_hud_badge"\n')
    f.write('        android:gravity="center_vertical"\n')
    f.write('        android:orientation="horizontal"\n')
    f.write('        android:paddingStart="@dimen/badge_padding_horizontal"\n')
    f.write('        android:paddingEnd="@dimen/badge_padding_horizontal"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@id/btnBack">\n\n')
    
    f.write('        <ImageView\n')
    f.write('            android:layout_width="@dimen/icon_size_small"\n')
    f.write('            android:layout_height="@dimen/icon_size_small"\n')
    f.write('            android:src="@drawable/ic_arrow_count"\n')
    f.write('            android:contentDescription="@string/arrows_left" />\n\n')
    
    f.write('        <TextView\n')
    f.write('            android:id="@+id/tvArrowCount"\n')
    f.write('            android:layout_width="wrap_content"\n')
    f.write('            android:layout_height="wrap_content"\n')
    f.write('            android:layout_marginStart="@dimen/spacing_6"\n')
    f.write('            android:textColor="@color/text_primary"\n')
    f.write('            android:textSize="@dimen/caption_text_size"\n')
    f.write('            android:textStyle="bold"\n')
    f.write('            tools:text="8" />\n')
    f.write('    </LinearLayout>\n\n')
    
    f.write('    <LinearLayout\n')
    f.write('        android:id="@+id/layoutLives"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="wrap_content"\n')
    f.write('        android:orientation="horizontal"\n')
    f.write('        app:layout_constraintBottom_toBottomOf="@id/badgeArrowCount"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toTopOf="@id/badgeArrowCount">\n\n')
    
    f.write('        <ImageView android:id="@+id/heart1" android:layout_width="@dimen/heart_size" android:layout_height="@dimen/heart_size" android:src="@drawable/ic_heart" android:contentDescription="@string/life_1" />\n')
    f.write('        <ImageView android:id="@+id/heart2" android:layout_width="@dimen/heart_size" android:layout_height="@dimen/heart_size" android:layout_marginStart="@dimen/spacing_8" android:src="@drawable/ic_heart" android:contentDescription="@string/life_2" />\n')
    f.write('        <ImageView android:id="@+id/heart3" android:layout_width="@dimen/heart_size" android:layout_height="@dimen/heart_size" android:layout_marginStart="@dimen/spacing_8" android:src="@drawable/ic_heart" android:contentDescription="@string/life_3" />\n')
    f.write('    </LinearLayout>\n\n')
    
    f.write('    <TextView\n')
    f.write('        android:id="@+id/tvDifficulty"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="@dimen/hud_height"\n')
    f.write('        android:layout_marginEnd="@dimen/spacing_16"\n')
    f.write('        android:background="@drawable/bg_hud_badge"\n')
    f.write('        android:gravity="center"\n')
    f.write('        android:paddingStart="@dimen/badge_padding_horizontal"\n')
    f.write('        android:paddingEnd="@dimen/badge_padding_horizontal"\n')
    f.write('        android:textColor="@color/text_secondary"\n')
    f.write('        android:textSize="@dimen/caption_text_size"\n')
    f.write('        android:textStyle="bold"\n')
    f.write('        app:layout_constraintBottom_toBottomOf="@id/badgeArrowCount"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintTop_toTopOf="@id/badgeArrowCount"\n')
    f.write('        tools:text="EASY" />\n\n')
    # Board
    f.write('    <FrameLayout\n')
    f.write('        android:id="@+id/boardContainer"\n')
    f.write('        android:layout_width="0dp"\n')
    f.write('        android:layout_height="0dp"\n')
    f.write('        android:layout_marginStart="@dimen/spacing_16"\n')
    f.write('        android:layout_marginEnd="@dimen/spacing_16"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_24"\n')
    f.write('        android:background="@drawable/bg_game_board"\n')
    f.write('        android:padding="@dimen/spacing_8"\n')
    f.write('        app:layout_constraintDimensionRatio="1:1"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@id/badgeArrowCount">\n\n')
    
    f.write('        <uz.kmax.arrowflow.ui.game.ArrowGridView\n')
    f.write('            android:id="@+id/gameBoard"\n')
    f.write('            android:layout_width="match_parent"\n')
    f.write('            android:layout_height="match_parent" />\n')
    f.write('    </FrameLayout>\n\n')
    
    # Bottom Bar
    f.write('    <LinearLayout\n')
    f.write('        android:id="@+id/bottomBar"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="wrap_content"\n')
    f.write('        android:layout_marginTop="@dimen/spacing_24"\n')
    f.write('        android:gravity="center"\n')
    f.write('        android:orientation="horizontal"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@id/boardContainer">\n\n')
    
    f.write('        <com.google.android.material.button.MaterialButton\n')
    f.write('            android:id="@+id/btnHint"\n')
    f.write('            android:layout_width="wrap_content"\n')
    f.write('            android:layout_height="wrap_content"\n')
    f.write('            android:layout_marginEnd="@dimen/spacing_8"\n')
    f.write('            android:backgroundTint="@color/button_hint_bg"\n')
    f.write('            android:text="@string/hint"\n')
    f.write('            app:icon="@android:drawable/ic_menu_help"\n')
    f.write('            style="@style/Widget.ArrowFlow.Button.Secondary" />\n\n')
    
    f.write('        <com.google.android.material.button.MaterialButton\n')
    f.write('            android:id="@+id/btnTool"\n')
    f.write('            android:layout_width="wrap_content"\n')
    f.write('            android:layout_height="wrap_content"\n')
    f.write('            android:layout_marginStart="@dimen/spacing_8"\n')
    f.write('            android:backgroundTint="@color/button_tool_bg"\n')
    f.write('            android:text="@string/undo"\n')
    f.write('            app:icon="@android:drawable/ic_menu_revert"\n')
    f.write('            style="@style/Widget.ArrowFlow.Button.Secondary" />\n')
    f.write('    </LinearLayout>\n\n')
    
    # Combo
    f.write('    <TextView\n')
    f.write('        android:id="@+id/tvCombo"\n')
    f.write('        android:layout_width="wrap_content"\n')
    f.write('        android:layout_height="wrap_content"\n')
    f.write('        android:elevation="8dp"\n')
    f.write('        android:textColor="@color/brand_gold"\n')
    f.write('        android:textSize="@dimen/combo_text_size"\n')
    f.write('        android:textStyle="bold"\n')
    f.write('        android:visibility="gone"\n')
    f.write('        app:layout_constraintBottom_toTopOf="@id/bottomBar"\n')
    f.write('        app:layout_constraintEnd_toEndOf="parent"\n')
    f.write('        app:layout_constraintStart_toStartOf="parent"\n')
    f.write('        app:layout_constraintTop_toBottomOf="@id/boardContainer"\n')
    f.write('        tools:text="COMBO x2"\n')
    f.write('        tools:visibility="visible" />\n\n')
    
    # Overlays
    f.write('    <include\n')
    f.write('        android:id="@+id/overlayGameStatus"\n')
    f.write('        layout="@layout/overlay_game_status" />\n\n')
    f.write('    <include\n')
    f.write('        android:id="@+id/overlayTutorial"\n')
    f.write('        layout="@layout/overlay_tutorial" />\n\n')
    
    f.write('</androidx.constraintlayout.widget.ConstraintLayout>\n')
    print('fragment_game.xml done')